### ISSUE TITLE
Don't re-notify of an issue if the notification already exists

### ISSUE THREAD

**Issue by tigerhawkvok** [Mygod/pogoplusle#14]
For example, a full box will buzz incessantly if - you're near stops. A better UX would be to only alert once and not alert again until the notification is dismissed.

(As an associated thing, dismiss that notification when the failed action occurs successfully)

**Comment by Mygod** [comment]
I'm not sure what you mean. This is what should happen and what is happening on my devices.

**Comment by tigerhawkvok** [comment]
Finally had a chance to get a screen recording of this when GPS wandering at the office. You can see the notification constantly firing the bag full notification, in such rapid succession that it never even disappears. 

https://photos.app.goo.gl/s88Jw1TMXF2BEBqD7

**Comment by Mygod** [comment]
Oh sorry. Repeated notifications of full bag/storage was intended behavior. I could consider in addition suppressing repeated notifications for full item bag since I can imagine that maybe you don't really care about having a full bag. I still think repeated notifications for catching errors still make sense.
