### ISSUE TITLE
Add switch for persistent notification

### ISSUE THREAD

**Issue by thoughtjunky** [Mygod/pogoplusle#32]
I would like the interaction counter to stay up when I hit 'clear' on my notification tray. 
*Samsung Fold4

**Comment by Belgmeister** [comment]
Was this actually applied?
For me the interaction counter still disappears upon hitting "clear" and acts as a regular notification.

An additional effect of this is that on a lot of smartwatches with a "simple" notification system (like Garmin watches), each interaction counter update also pings as a normal notification instead of being "silent" as a permanent notifications do.
